/*
 * libcpp_threads.c -- libc++ external threading hooks (minimal placeholder).
 *
 * Generated by lib-build for variant cortex-m33-hard-fpv5-sp-d16 (arm-none-eabi).
 *
 * libc++ was built with `LIBCXX_HAS_EXTERNAL_THREAD_API=ON`, which
 * means it calls these `__libcpp_*` functions whenever you use
 * `std::mutex`, `std::thread`, `std::call_once`, etc. This file only
 * provides a minimal placeholder implementation:
 *
 * 1. Some applications may link with this as-is if they do not exercise
 *    real threading behaviour.
 * 2. Any real scheduler / RTOS integration must replace these bodies.
 * 3. Any code path that depends on per-thread state or TLS must also
 *    provide working `__libcpp_tls_*` glue plus the lower-level TLS
 *    runtime integration for thread creation, switching and teardown.
 *
 * To integrate with FreeRTOS / Zephyr / CMSIS-RTOS2, replace each
 * body with a call into your RTOS. Examples at the bottom.
 *
 * The linker only pulls in the symbols your C++ code actually uses, so
 * the placeholder can be enough to get started. Treat that as a staging
 * convenience, not as proof that the implementation is complete.
 */

#include <stdbool.h>
#include <stddef.h>
#include <time.h>

/* Opaque types -- must match the typedefs in <__external_threading>. */
typedef void *         __libcpp_mutex_t;
typedef void *         __libcpp_recursive_mutex_t;
typedef void *         __libcpp_condvar_t;
typedef int            __libcpp_exec_once_flag;
typedef void *         __libcpp_thread_t;
typedef unsigned long  __libcpp_thread_id;
typedef unsigned long  __libcpp_tls_key;

/* =========================================================================
 *   Mutex (std::mutex)
 * ========================================================================= */

int  __libcpp_mutex_lock    (__libcpp_mutex_t *m) { (void) m; return 0; }
bool __libcpp_mutex_trylock (__libcpp_mutex_t *m) { (void) m; return true; }
int  __libcpp_mutex_unlock  (__libcpp_mutex_t *m) { (void) m; return 0; }
int  __libcpp_mutex_destroy (__libcpp_mutex_t *m) { (void) m; return 0; }

int  __libcpp_recursive_mutex_init    (__libcpp_recursive_mutex_t *m) { (void) m; return 0; }
int  __libcpp_recursive_mutex_lock    (__libcpp_recursive_mutex_t *m) { (void) m; return 0; }
bool __libcpp_recursive_mutex_trylock (__libcpp_recursive_mutex_t *m) { (void) m; return true; }
int  __libcpp_recursive_mutex_unlock  (__libcpp_recursive_mutex_t *m) { (void) m; return 0; }
int  __libcpp_recursive_mutex_destroy (__libcpp_recursive_mutex_t *m) { (void) m; return 0; }

/* =========================================================================
 *   Condition variable (std::condition_variable)
 * ========================================================================= */

int __libcpp_condvar_signal   (__libcpp_condvar_t *c)                                 { (void) c; return 0; }
int __libcpp_condvar_broadcast(__libcpp_condvar_t *c)                                 { (void) c; return 0; }
int __libcpp_condvar_wait     (__libcpp_condvar_t *c, __libcpp_mutex_t *m)            { (void) c; (void) m; return 0; }
int __libcpp_condvar_timedwait(__libcpp_condvar_t *c, __libcpp_mutex_t *m,
                               struct timespec *ts)                                   { (void) c; (void) m; (void) ts; return 0; }
int __libcpp_condvar_destroy  (__libcpp_condvar_t *c)                                 { (void) c; return 0; }

/* =========================================================================
 *   One-time init (std::call_once)
 * ========================================================================= */

int __libcpp_execute_once(__libcpp_exec_once_flag *flag, void (*init)(void))
{
    if (*flag == 0) {
        *flag = 1;
        init();
    }
    return 0;
}

/* =========================================================================
 *   Thread identity + lifecycle (std::thread)
 *
 *   This placeholder pretends every thread has id 1 and runs newly
 *   created work inline. That is only suitable as a link-time stub,
 *   not as a conforming threading implementation.
 * ========================================================================= */

bool __libcpp_thread_id_equal(__libcpp_thread_id a, __libcpp_thread_id b) { return a == b; }
bool __libcpp_thread_id_less (__libcpp_thread_id a, __libcpp_thread_id b) { return a <  b; }

bool __libcpp_thread_isnull(const __libcpp_thread_t *t) { return *t == NULL; }

int __libcpp_thread_create(__libcpp_thread_t *t, void *(*fn)(void *), void *arg)
{
    (void) t;
    fn(arg);                       /* no scheduler: run synchronously */
    return 0;
}

__libcpp_thread_id __libcpp_thread_get_current_id(void) { return 1; }
__libcpp_thread_id __libcpp_thread_get_id(const __libcpp_thread_t *t) { (void) t; return 1; }

int  __libcpp_thread_join  (__libcpp_thread_t *t) { (void) t; return 0; }
int  __libcpp_thread_detach(__libcpp_thread_t *t) { (void) t; return 0; }
void __libcpp_thread_yield (void)                 { /* no-op */      }

/* Called by std::this_thread::sleep_for(). Busy-loop for the given ns
 * count -- replace with a real delay if your board has a tick source. */
void __libcpp_thread_sleep_for_ns(long long ns)
{
    volatile long long i = ns / 100;
    while (i-- > 0) { __asm__ volatile("nop"); }
}

/* =========================================================================
 *   TLS keys
 *
 *   This is only enough to satisfy the linker for code paths that never
 *   require real per-thread storage. If your firmware or libraries use
 *   `thread_local`, `errno`, `std::promise`, `std::async`, or any path
 *   that expects real per-thread state, replace this with a real TLS
 *   integration that cooperates with your runtime and scheduler.
 * ========================================================================= */

int __libcpp_tls_create(__libcpp_tls_key *key, void (*dtor)(void *))
{
    (void) dtor;
    static unsigned long next_key = 1;
    *key = next_key++;
    return 0;
}

void *__libcpp_tls_get(__libcpp_tls_key key)           { (void) key; return NULL; }
int   __libcpp_tls_set(__libcpp_tls_key key, void *v)  { (void) key; (void) v; return 0; }

/* =========================================================================
 *   FreeRTOS integration sketch (uncomment and adapt)
 * =========================================================================
 *
 * #include <FreeRTOS.h>
 * #include <semphr.h>
 * #include <task.h>
 *
 * int __libcpp_mutex_lock(__libcpp_mutex_t *m) {
 *     if (*m == NULL) *m = xSemaphoreCreateMutex();
 *     return xSemaphoreTake((SemaphoreHandle_t) *m, portMAX_DELAY) == pdTRUE ? 0 : -1;
 * }
 * int __libcpp_mutex_unlock(__libcpp_mutex_t *m) {
 *     return xSemaphoreGive((SemaphoreHandle_t) *m) == pdTRUE ? 0 : -1;
 * }
 * bool __libcpp_mutex_trylock(__libcpp_mutex_t *m) {
 *     if (*m == NULL) *m = xSemaphoreCreateMutex();
 *     return xSemaphoreTake((SemaphoreHandle_t) *m, 0) == pdTRUE;
 * }
 * int __libcpp_mutex_destroy(__libcpp_mutex_t *m) {
 *     if (*m) vSemaphoreDelete((SemaphoreHandle_t) *m);
 *     *m = NULL;
 *     return 0;
 * }
 *
 * int __libcpp_thread_create(__libcpp_thread_t *t, void *(*fn)(void *), void *arg) {
 *     TaskHandle_t h;
 *     if (xTaskCreate((TaskFunction_t) fn, "cxx", 1024, arg,
 *                     tskIDLE_PRIORITY + 1, &h) != pdPASS) return -1;
 *     *t = h;
 *     return 0;
 * }
 * void __libcpp_thread_yield(void) { taskYIELD(); }
 * void __libcpp_thread_sleep_for_ns(long long ns) {
 *     TickType_t ticks = (TickType_t) (ns / (1000000000ULL / configTICK_RATE_HZ));
 *     vTaskDelay(ticks ? ticks : 1);
 * }
 */
