/*
 * main.cpp -- minimal hello-world using libc++ containers.
 *
 * Generated by lib-build for variant cortex-m33-hard-fpv5-sp-d16 (arm-none-eabi).
 */

#include <array>
#include <cstdio>
#include <mutex>
#include <numeric>

// The rest of the firmware is expected to override `board_putc` (see
// syscalls.c) so that printf actually comes out of a UART.
extern "C" int board_putc(int);

int main()
{
    std::array<int, 8> xs{};
    std::iota(xs.begin(), xs.end(), 1);                  // 1..8

    int sum = 0;
    {
        // Exercises the __libcpp_mutex_* hooks in libcpp_threads.c.
        static std::mutex m;
        std::lock_guard<std::mutex> g{m};
        for (int v : xs) sum += v;
    }

    std::printf("hello from cortex-m33-hard-fpv5-sp-d16, sum=%d\n", sum);
    return 0;
}
