/*
 * startup.c -- Cortex-M reset handler + interrupt vector table.
 *
 * Generated by lib-build for variant cortex-m33-hard-fpv5-sp-d16 (arm-none-eabi).
 *
 * Responsibilities of this file (things crt0.o does NOT do for you):
 *   1. Interrupt vector table placed at the start of flash.
 *   2. Set the Main Stack Pointer (vector[0]).
 *   3. Enable the FPU in CPACR before any floating-point instruction.
 *   4. Call SystemInit() (clocks / PLL, weak so it's optional).
 *   5. Jump to picolibc's `_start`, which does:
 *        .bss zero-fill, .data copy, TLS init, C++ ctors, main, _exit.
 *
 * Style note: every optional symbol attaches `__attribute__((weak))` at
 * its definition (never on a separate declaration). This keeps the
 * "which line owns the attribute" question from ever coming up, and
 * lets the reader find the attribute by jumping to the function body.
 */

#include <stdint.h>

/* ---- Linker symbol + picolibc entry ------------------------------------ */

extern uint32_t __stack;                                 /* from linker script */
extern void     _start(void) __attribute__((noreturn));  /* in picolibc crt0.o */

/* ---- FPU enable -------------------------------------------------------- */

static inline void fpu_enable(void)
{
    /* CPACR bits 20..23: enable CP10 and CP11 (single + double
     * precision FPU access). Required before executing any
     * floating-point instruction on Cortex-M3+FPU and later. */
    volatile unsigned int *CPACR = (volatile unsigned int *)0xE000ED88;
    *CPACR |= (0xFu << 20);
    __asm__ volatile("dsb; isb");
}

/* ---- Default handler for unimplemented interrupts ----------------------
 *
 * Weak so a board can override with a common "something went wrong" trap.
 */

__attribute__((weak))
void Default_Handler(void)
{
    for (;;) { /* set a breakpoint here while debugging */ }
}

/* ---- Core exceptions: weak aliases that redirect to Default_Handler ----
 *
 * Attribute placement: `weak, alias(...)` MUST live on the definition.
 * clang/gcc both reject alias attributes on plain declarations, so each
 * of these IS the definition (it has no separate function body -- the
 * alias is the body).
 */

#define DECLARE_IRQ(name)                                                   \
    __attribute__((weak, alias("Default_Handler")))                         \
    void name(void)

DECLARE_IRQ(NMI_Handler);
DECLARE_IRQ(HardFault_Handler);
DECLARE_IRQ(MemManage_Handler);
DECLARE_IRQ(BusFault_Handler);
DECLARE_IRQ(UsageFault_Handler);
DECLARE_IRQ(SecureFault_Handler);       /* Armv8-M only; harmless on v7-M */
DECLARE_IRQ(SVC_Handler);
DECLARE_IRQ(DebugMon_Handler);
DECLARE_IRQ(PendSV_Handler);
DECLARE_IRQ(SysTick_Handler);

/* TODO: your chip's peripheral IRQ handlers go here (and in the vector
 *       table below). Follow the same DECLARE_IRQ(NAME); pattern.        */

/* ---- Optional board hooks --------------------------------------------- */

__attribute__((weak))
void SystemInit(void)
{
    /* Override in your board TU to configure clocks, PLL, VTOR. */
}

/* ---- Reset handler ----------------------------------------------------- */

__attribute__((noreturn))
void Reset_Handler(void)
{
    fpu_enable();
    SystemInit();
    _start();                /* jumps into picolibc crt0 */
    for (;;) { }             /* _start is noreturn; this is defensive */
}

/* ---- Interrupt vector table (must land at flash origin) ---------------- */

__attribute__((used, section(".isr_vector")))
void (* const g_pfnVectors[])(void) = {
    (void (*)(void)) &__stack,   /* 0x00: initial Main Stack Pointer    */
    Reset_Handler,               /* 0x04                                */
    NMI_Handler,                 /* 0x08                                */
    HardFault_Handler,           /* 0x0C                                */
    MemManage_Handler,           /* 0x10                                */
    BusFault_Handler,            /* 0x14                                */
    UsageFault_Handler,          /* 0x18                                */
    SecureFault_Handler,         /* 0x1C (Armv8-M)                      */
    0, 0, 0,                     /* 0x20..0x28 reserved                 */
    SVC_Handler,                 /* 0x2C                                */
    DebugMon_Handler,            /* 0x30                                */
    0,                           /* 0x34 reserved                       */
    PendSV_Handler,              /* 0x38                                */
    SysTick_Handler,             /* 0x3C                                */
    /* Append your peripheral IRQ handlers here, in vector-number order. */
};
