/*
 * syscalls.c -- minimum POSIX-style backends picolibc requires.
 *
 * Generated by lib-build for variant cortex-m33-hard-fpv5-sp-d16 (arm-none-eabi).
 *
 * picolibc was built with `-Dposix-console=true`, which forwards
 * stdio to POSIX-style `read` / `write` hooks on this target. Implement
 * them against your board's UART / USB CDC / ITM / whatever.
 *
 * `sbrk` backs malloc(). The default implementation is a bump allocator
 * constrained by `_end` and `__heap_end`, which must come from your
 * linker script. Replace it with your RTOS heap if you prefer.
 *
 * `clock_gettime(CLOCK_MONOTONIC, ...)` is required by libc++'s
 * std::chrono::steady_clock. You must wire it to a real monotonic source
 * such as a hardware timer, SysTick-derived counter, or RTOS tick API.
 */

#include <errno.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#include "rtt.h"

#undef errno
extern int errno;

ssize_t write(int fd, const void *buf, size_t len)
{
    if (fd == 1 || fd == 2) {
        const char *p = (const char *) buf;
        rtt_write(p, len);
        return (ssize_t) len;
    }
    errno = EBADF;
    return -1;
}

ssize_t read(int fd, void *buf, size_t len)
{
    if (fd == 0) {
        char *p = (char *) buf;
        return (ssize_t) rtt_read(p, len);
    }
    errno = EBADF;
    return -1;
}

int close(int fd) { (void) fd; errno = EBADF; return -1; }

int fstat(int fd, struct stat *st)
{
    (void) fd;
    st->st_mode = S_IFCHR;       /* treat every fd as a terminal */
    return 0;
}

int isatty(int fd) { (void) fd; return 1; }

off_t lseek(int fd, off_t off, int whence)
{
    (void) fd; (void) off; (void) whence;
    errno = ESPIPE;
    return -1;
}

/* ---- heap (for malloc) --------------------------------------------------- */
extern char _end;            /* from linker script: heap start */
extern char __heap_end;      /* from linker script: heap upper bound (exclusive) */

void *sbrk(ptrdiff_t incr)
{
    static char *heap_ptr = 0;
    char *prev;

    if (heap_ptr == 0) {
        heap_ptr = &_end;
    }
    if (heap_ptr + incr > &__heap_end) {
        errno = ENOMEM;
        return (void *) -1;
    }
    prev = heap_ptr;
    heap_ptr += incr;
    return prev;
}

/* ---- monotonic clock (libc++ chrono::steady_clock) ----------------------- */

int clock_gettime(clockid_t clk_id, struct timespec *tp)
{
    (void) clk_id;
    /* Replace this placeholder with a real monotonic source. Returning
     * a constant time will break steady_clock timeouts and sleeps. */
    uint64_t ns = 0;
    tp->tv_sec  = (time_t) (ns / 1000000000ULL);
    tp->tv_nsec = (long)   (ns % 1000000000ULL);
    return 0;
}

/* ---- program exit -------------------------------------------------------- */

void _exit(int status) __attribute__((noreturn));
void _exit(int status)
{
    (void) status;
    for (;;) { /* set a breakpoint to catch main() returning */ }
}
