# -----------------------------------------------------------------------------
# toolchain.cmake -- clang cross-compilation for variant cortex-m33-hard-fpv5-sp-d16 (arm-none-eabi).
#
# Generated by lib-build. Use with:
#
#   cmake -B build -G Ninja \
#         -DCMAKE_TOOLCHAIN_FILE=./toolchain.cmake \
#         -DSDK_ROOT=E:/lib-build/out/arm-none-eabi/cortex-m33-hard-fpv5-sp-d16
#
# -----------------------------------------------------------------------------

set(CMAKE_SYSTEM_NAME      Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# Host clang + LLVM binutils. Adjust paths if not on PATH.
set(CMAKE_C_COMPILER   clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_AR           llvm-ar)
set(CMAKE_RANLIB       llvm-ranlib)
set(CMAKE_LINKER       ld.lld)

# Architecture-level flags baked in at configure time. These must match the
# flags the lib-build tool used when it produced the libraries under
# SDK_ROOT; mixing e.g. -mfloat-abi=soft code with a hard-float libc++
# results in undefined behaviour or link errors.
set(_arch_flags "--target=arm-none-eabi;-mcpu=cortex-m33;-mfloat-abi=hard;-mfpu=fpv5-sp-d16")
foreach(f IN LISTS _arch_flags)
    string(APPEND CMAKE_C_FLAGS_INIT   " ${f}")
    string(APPEND CMAKE_CXX_FLAGS_INIT " ${f}")
    string(APPEND CMAKE_ASM_FLAGS_INIT " ${f}")
endforeach()

# Default the SDK root to the directory containing THIS toolchain file.
# Override with -DSDK_ROOT=... if you moved things around.
if(NOT DEFINED SDK_ROOT)
    get_filename_component(SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
set(SDK_ROOT "${SDK_ROOT}" CACHE PATH "lib-build install root for this variant")

# Let CMake find headers and libraries inside the sysroot only.
set(CMAKE_SYSROOT "${SDK_ROOT}/picolibc")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
